### ISSUE TITLE
Enhance auth0 setup part 4 : rule

### ISSUE THREAD

**Issue by Manawasp** [auth0-samples/auth0-multitenant-website#14]
Hello,

I try to setup an auth0 multitenant but end up with an error `Cannot read property 'map' of undefined` after a successful login
After some research look like something is wrong in my rule asked by the last point in auth0 setup.

From the link I found this rule :
```javascript
function (user, context, callback) {
  var namespace = 'http://yourdomain/claims/'; // You can set your own namespace, but do not use an Auth0 domain

  // Add the namespaced tokens. Remove any which is not necessary for your scenario
  context.idToken[namespace + "permissions"] = user.permissions;
  context.idToken[namespace + "groups"] = user.groups;
  context.idToken[namespace + "roles"] = user.roles;
  
  callback(null, user, context);
}
```
Note:
- Link https://auth0.com/docs/extensions/authorization-extension#controlling-application-access
- Then I jump to `Add Functionality` and `Use the Authorization Extension's Data in Rules`

This rule make me got (user1)
```
{ 'http://yourdomain/claims/groups': [ 'tenant1' ],
  'http://yourdomain/claims/roles': [ 'Tenant User' ] }
```

But the application want "groups" not an url, so inside of the rule I removed the namespace but doesn't help, I got nothing in return.

- Did I take the wrong rule (didn't see other one) ? Documentation from the given link has been updated ?

Thanks

**Comment by sgmeyer** [comment]
@Manawasp the problem is this code doesn't account for namespaces in the claim.  I've pushed a change that fixes this.  This will require a couple tweaks in your setup.

First, your rule uses the namespace `http://yourdomain/claims/`.  In my code I am expecting: `https://{process.env.ROOT_DOMAINt}/claims/...`.  The `{ROOT_DOMAIN}` piece should be the same value your configured in your `.env` file.  

Here is how I configured my rule:

```
function (user, context, callback) {
  var namespace = 'http://yourcompany.com/claims/'; // You can set your own namespace, but do not use an Auth0 domain

  // Add the namespaced tokens. Remove any which is not necessary for your scenario
  context.idToken[namespace + "permissions"] = user.permissions;
  context.idToken[namespace + "groups"] = user.groups;
  context.idToken[namespace + "roles"] = user.roles;
  
  return callback(null, user, context);
}
```

**Comment by sgmeyer** [comment]
This morning I went a head and update those steps to include the rule.  The previous link is gone.  Now the rule is embedded in the instructions.

**Comment by Manawasp** [comment]
Hi @sgmeyer, thanks for the update, I tried and noticed 2 missing update which use the old way to get groups from the payload :
- **routes/user.js** l.15 in `router.get('/', ...., function(req, res) {...`
- **lib/tenant.js** l.10 in `getAuthorizedTenants`
